version: "3"
# for each of those services, we will run the docker file associated in the folder
services:
  db:
    image: 'postgres'
    container_name: leisure-nexus-db
    networks:
      - infra
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    ports:
      - "5432:5432"
  app:
    image: gologicben/leisure-nexus
    container_name: leisure-nexus-app
    networks:
      - infra
    depends_on:
      - "db"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD-SHELL", "curl https://leisure-nexus.acc.gologic.ca/" ]
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 20s
    labels:
      - traefik.enable=true
      - traefik.docker.network=infra
      - traefik.http.routers.godevopsapi.entrypoints=web
      - traefik.http.routers.godevopsapi.rule=Host(`leisure-nexus.acc.gologic.ca`)
      - traefik.http.routers.godevopsapi.middlewares=godevopsapi-redirectregex
      - traefik.http.routers.godevopsapi-tls.entrypoints=websecure
      - traefik.http.routers.godevopsapi-tls.tls=true
      - traefik.http.routers.godevopsapi-tls.tls.certresolver=gologic
      - traefik.http.routers.godevopsapi-tls.rule=Host(`leisure-nexus.acc.gologic.ca`)
      - traefik.http.middlewares.godevopsapi-redirectregex.redirectregex.regex=^(http|https)://(.*?)/(.*)
      - traefik.http.middlewares.godevopsapi-redirectregex.redirectregex.replacement=https://leisure-nexus.acc.gologic.ca/$${3}

networks:
  infra:
    external:
      name: infra