spring:
  jpa:
    show-sql: false # DEBUG JPA/SQL
  datasource:
    url: jdbc:h2:mem:devdb
logging.level.root: INFO 
#logging.level.org.hibernate.SQL: DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE
