spring:
  jpa:
    show-sql: false # DEBUG JPA/SQL
  datasource:
    url: jdbc:h2:mem:devdb
    
logging.level.root: INFO 
logging.level.io.v47.tmdb: DEBUG
#logging.level.org.hibernate.SQL: DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE

database:
   imdb:
      api-key: k_1216yup9
   tmdb:
      api-key: b29cc04446d224df94d186a7918fc788

# apiket for TMBD and this property allow third-party lib to autoconfire tmdbClient
tmdb-client.api-key: b29cc04446d224df94d186a7918fc788